version: "3.8"
services:
  eureka:
    build: /usr/local/aprilApp/eureka-server
    image: eureka-server
    ports:
    - "7001:7001"
  provider:
    build: /usr/local/aprilApp/db-provider
    image: provider-server
    ports:
    - "8001:8001"
  consumer:
    build: /usr/local/aprilApp/db-consumer
    image: consumer-server
    ports:
    - "8002:8002"

